-- =============================================================================
-- JOB PURGE RGPD - GÉNÉRATION RAPPORT (AVANT / APRÈS)
-- =============================================================================
-- Ce script produit UN seul jeu de résultats avec tous les comptages,
-- pour faciliter l'export (CSV/Excel) et la comparaison avant/après.
--
-- Utilisation:
--   1. AVANT le job : exécuter le script, exporter le résultat (ex: rapport_avant.csv).
--   2. Lancer le job de purge.
--   3. APRÈS le job : ré-exécuter le script, exporter (ex: rapport_apres.csv).
--   4. Comparer : les comptages "après" doivent être 0 pour toutes les lignes
--      liées aux bénéficiaires purgés.
--
-- Paramètre : DEFINE mois_anonymisation = -24
-- =============================================================================

DEFINE mois_anonymisation = -24

PROMPT Génération rapport purge RGPD - mois_anonymisation=&mois_anonymisation
PROMPT Exécution: 
SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS') FROM DUAL;
PROMPT

-- Rapport sous forme d'une seule requête UNION pour export facile
SELECT '1_BENEFICIAIRES_ELIGIBLES' AS libelle, COUNT(*) AS nombre
FROM BENEFICIAIRE
WHERE DATE_ANONYMISATION IS NOT NULL
  AND DATE_ANONYMISATION < ADD_MONTHS(SYSDATE, &mois_anonymisation)
UNION ALL
SELECT '2_LIEN_REGUL_BENEF_DECLARATION', COUNT(*)
FROM LIEN_REGUL_BENEF_DECLARATION lrbd
WHERE lrbd.ID_REGULARISATION IN (
  SELECT ID FROM REGULARISATION_BENEFICIAIRE
  WHERE ID_BENEFICIAIRE IN (
    SELECT ID FROM BENEFICIAIRE
    WHERE DATE_ANONYMISATION IS NOT NULL AND DATE_ANONYMISATION < ADD_MONTHS(SYSDATE, &mois_anonymisation)
  )
)
UNION ALL
SELECT '3_LIEN_VERSEMENT_DECLARATION', COUNT(*)
FROM LIEN_VERSEMENT_DECLARATION lvd
WHERE lvd.ID_VERSEMENT IN (
  SELECT ID FROM VERSEMENT
  WHERE ID_BENEFICIAIRE IN (
    SELECT ID FROM BENEFICIAIRE
    WHERE DATE_ANONYMISATION IS NOT NULL AND DATE_ANONYMISATION < ADD_MONTHS(SYSDATE, &mois_anonymisation)
  )
)
UNION ALL
SELECT '4_LIEN_REGUL_VERS_DECLARATION', COUNT(*)
FROM LIEN_REGUL_VERS_DECLARATION lrvd
WHERE lrvd.ID_REGULARISATION IN (
  SELECT RV.ID FROM REGULARISATION_VERSEMENT RV
  JOIN VERSEMENT V ON V.ID = RV.ID_VERSEMENT
  WHERE V.ID_BENEFICIAIRE IN (
    SELECT ID FROM BENEFICIAIRE
    WHERE DATE_ANONYMISATION IS NOT NULL AND DATE_ANONYMISATION < ADD_MONTHS(SYSDATE, &mois_anonymisation)
  )
)
UNION ALL
SELECT '5_LIEN_BENEF_DECLARATION', COUNT(*)
FROM LIEN_BENEF_DECLARATION
WHERE ID_BENEFICIAIRE IN (
  SELECT ID FROM BENEFICIAIRE
  WHERE DATE_ANONYMISATION IS NOT NULL AND DATE_ANONYMISATION < ADD_MONTHS(SYSDATE, &mois_anonymisation)
)
UNION ALL
SELECT '6_CONTRIB_SOC_RGUR', COUNT(*)
FROM CONTRIBUTION_SOCIALE
WHERE CODE_TYPE_PAIEMENT = 'RGUR' AND ID_PAIEMENT IN (
  SELECT RV.ID FROM REGULARISATION_VERSEMENT RV
  JOIN VERSEMENT V ON V.ID = RV.ID_VERSEMENT
  WHERE V.ID_BENEFICIAIRE IN (
    SELECT ID FROM BENEFICIAIRE
    WHERE DATE_ANONYMISATION IS NOT NULL AND DATE_ANONYMISATION < ADD_MONTHS(SYSDATE, &mois_anonymisation)
  )
)
UNION ALL
SELECT '7_CONTRIB_SOC_REGL', COUNT(*)
FROM CONTRIBUTION_SOCIALE
WHERE CODE_TYPE_PAIEMENT = 'REGL' AND ID_PAIEMENT IN (
  SELECT ID FROM VERSEMENT
  WHERE ID_BENEFICIAIRE IN (
    SELECT ID FROM BENEFICIAIRE
    WHERE DATE_ANONYMISATION IS NOT NULL AND DATE_ANONYMISATION < ADD_MONTHS(SYSDATE, &mois_anonymisation)
  )
)
UNION ALL
SELECT '8_CONTRIB_SOC_RGUB', COUNT(*)
FROM CONTRIBUTION_SOCIALE
WHERE CODE_TYPE_PAIEMENT = 'RGUB' AND ID_PAIEMENT IN (
  SELECT ID FROM REGULARISATION_BENEFICIAIRE
  WHERE ID_BENEFICIAIRE IN (
    SELECT ID FROM BENEFICIAIRE
    WHERE DATE_ANONYMISATION IS NOT NULL AND DATE_ANONYMISATION < ADD_MONTHS(SYSDATE, &mois_anonymisation)
  )
)
UNION ALL
SELECT '9_HISTO_TAUX_BENEFICIAIRE', COUNT(*)
FROM HISTO_TAUX_BENEFICIAIRE
WHERE ID_BENEFICIAIRE IN (
  SELECT ID FROM BENEFICIAIRE
  WHERE DATE_ANONYMISATION IS NOT NULL AND DATE_ANONYMISATION < ADD_MONTHS(SYSDATE, &mois_anonymisation)
)
UNION ALL
SELECT '10_HISTO_BENEFICIAIRE', COUNT(*)
FROM HISTO_BENEFICIAIRE
WHERE ID_BENEFICIAIRE IN (
  SELECT ID FROM BENEFICIAIRE
  WHERE DATE_ANONYMISATION IS NOT NULL AND DATE_ANONYMISATION < ADD_MONTHS(SYSDATE, &mois_anonymisation)
)
UNION ALL
SELECT '11_DECLARATION_AMORCAGE_TAUX', COUNT(*)
FROM DECLARATION_AMORCAGE_TAUX
WHERE ID_BENEFICIAIRE IN (
  SELECT ID FROM BENEFICIAIRE
  WHERE DATE_ANONYMISATION IS NOT NULL AND DATE_ANONYMISATION < ADD_MONTHS(SYSDATE, &mois_anonymisation)
)
UNION ALL
SELECT '12_REGULARISATION_VERSEMENT', COUNT(*)
FROM REGULARISATION_VERSEMENT
WHERE ID_VERSEMENT IN (
  SELECT ID FROM VERSEMENT
  WHERE ID_BENEFICIAIRE IN (
    SELECT ID FROM BENEFICIAIRE
    WHERE DATE_ANONYMISATION IS NOT NULL AND DATE_ANONYMISATION < ADD_MONTHS(SYSDATE, &mois_anonymisation)
  )
)
UNION ALL
SELECT '13_VERSEMENT', COUNT(*)
FROM VERSEMENT
WHERE ID_BENEFICIAIRE IN (
  SELECT ID FROM BENEFICIAIRE
  WHERE DATE_ANONYMISATION IS NOT NULL AND DATE_ANONYMISATION < ADD_MONTHS(SYSDATE, &mois_anonymisation)
)
UNION ALL
SELECT '14_REGULARISATION_BENEFICIAIRE', COUNT(*)
FROM REGULARISATION_BENEFICIAIRE
WHERE ID_BENEFICIAIRE IN (
  SELECT ID FROM BENEFICIAIRE
  WHERE DATE_ANONYMISATION IS NOT NULL AND DATE_ANONYMISATION < ADD_MONTHS(SYSDATE, &mois_anonymisation)
)
UNION ALL
SELECT '15_HISTO_TAUX_INDIVIDU', COUNT(*)
FROM HISTO_TAUX_INDIVIDU
WHERE ID_INDIVIDU IN (SELECT ID FROM INDIVIDU WHERE NIR IS NULL)
UNION ALL
SELECT '16_HISTO_DONNEES_INDIVIDU', COUNT(*)
FROM HISTO_DONNEES_INDIVIDU
WHERE ID_INDIVIDU IN (SELECT ID FROM INDIVIDU WHERE NIR IS NULL)
UNION ALL
SELECT '17_INDIVIDU_NIR_NULL', COUNT(*)
FROM INDIVIDU
WHERE NIR IS NULL
ORDER BY 1;

PROMPT
PROMPT Exportez ce résultat en CSV. Après le job, ré-exécutez et comparez (nombres attendus à 0).
